### PR TITLE
Make php runtime backward compatible

### PR DESCRIPTION
**Pull request by sunloverz**

### CODE REVIEW

**Comment by sunloverz** [comment]
@thousandsofthem could you please review

**Comment by nodesocket** [comment]
You are missing changing:

https://github.com/sunloverz/iron_worker_ruby_ng/blob/php-runtime-fix/lib/iron_worker_ng/code/runtime/php.rb#L48

**Comment by sunloverz** [comment]
@nodesocket it was already `$assoc = false` there

**Comment by nodesocket** [comment]
@sunloverz 

Hum, then why did running:

    $payload = getPayload();

Return an array instead of object if it was already:

    $assoc = false

**Comment by thousandsofthem** [comment]
backward compatible default for getArgs() and getConfig( is assoc=true (equal to "return an array")

e.g. https://github.com/iron-io/iron_worker_php/blob/master/IronWorker.class.php#L803

no changes (in code) required. closing this pull request.

**Pull request closed without merging**
