### PR TITLE
Fix uploading using the patch command 

### PR DESCRIPTION
**Pull request by sunloverz**

### CODE REVIEW

**Comment by sunloverz** [comment]
@thousandsofthem could you please review

**Comment by thousandsofthem** [comment]
Doesn't looks like a fix, more like change in behavior. Is it really broken?

**Comment by sunloverz** [comment]
@thousandsofthem 
When passing a patch file It raises such error 
```
/home/tyler/.rvm/gems/ruby-2.1.4@teddy/gems/iron_core-1.0.3/lib/iron_core/iron_logger.rb:50:in `raise_exception': Error while patching worker (IronCore::Error)
can't find file to patch at input line 3
```
And I think its better to pass a whole file for patching than creating a patch file then sending it

**Comment by thousandsofthem** [comment]
Still thinking it's wrong input format, not the broken code. anyway, current method is not documented and not really user-friendly, let's try your proposal.

Code looks really good! (didn't tested it yet though) Some notes:

1) Please add to readme real-world-like example, not just syntax reference. e.g. can't understand how it works without reading the code

2) Please test will it work with passing multiple files at once (add to readme an example how to do it)
Seems like need modification in `system("cat patch/\...` line

3) Please add "simple" mode where both local and worker's files named equally, e.g. exec.rb -> exec.rb

**Comment by sunloverz** [comment]
> 2) Please test will it work with passing multiple files at once (add to readme an example how to do it)
Seems like need modification in system("cat patch/\... line

Now it can pass only 2 files (a target file and new file), maybe you have a better idea how to pass multiple files?

**Comment by thousandsofthem** [comment]
Possible alternative:
```sh
$ iron_worker patch --file foo1.rb=lib/bar.rb --file foo2.rb  --file foo3.rb
```

**Comment by sunloverz** [comment]
@thousandsofthem added some changes

**Comment by sunloverz** [comment]
> i thought it's in SOURCE=>DESTINATION format but it appears to be otherwise. do you think DESTINATION => SOURCE format is ok? 
You are right
> there are no mentions about right format either (in readme)
In python it will be .py, in ruby .rb, etc. quite clear

**Comment by thousandsofthem** [comment]
>> DESTINATION => SOURCE format is ok? 
You are right
there are no mentions about right format either (in readme)

> In python it will be .py, in ruby .rb, etc. quite clear

.rb etc is just a file extension. i mean what "foo.rb=bar.rb" string means

**Comment by sunloverz** [comment]
It means DESTINATION => SOURCE
I will change it to SOURCE => DESTINATION and remind about it in readme

**Comment by thousandsofthem** [comment]
Thanks!

**Comment by sunloverz** [comment]
Done

**Comment by thousandsofthem** [comment]
Thanks! looks good. Going to test it

**Comment by thousandsofthem** [comment]
Don't work for me.

```sh
$ iron_worker upload simple/simple.worker&& iron_worker queue simple --wait
...
OK
$ iron_worker patch simple -p 'simple/foo.rb=foo.rb,simple/bar.rb=bar.rb'
------> Creating client
        Project 'Testing - actual' with id='4fa1ed670c389d3f9b00218c'
------> Patching code package 'simple'
        Can't find code with name='simple' to patch
/Users/pocketmoon/.rvm/gems/ruby-2.1.4/gems/iron_core-1.0.5/lib/iron_core/iron_logger.rb:50:in `raise_exception': Can't find code with name='simple' to patch (IronCore::Error)
```

**Comment by sunloverz** [comment]
Uploading and patching this code https://github.com/iron-io/iron_worker_examples/tree/master/ruby_ng/hello_worker
```
tyler@durden ~/test $ iron_worker upload hello 
------> Creating client
        Project 'test' with id='54af65073f116c000500008d'
------> Creating code package
        Found workerfile with path='hello.worker'
        Detected exec with path='hello_worker.rb' and args='{}'
        Code package name is 'hello'
------> Uploading code package 'hello'
        Code package uploaded with id='54afe12308cf462b2a0172ff' and revision='1'
        Check 'https://hud.iron.io/tq/projects/54af65073f116c000500008d/code/54afe12308cf462b2a0172ff' for more info
tyler@durden ~/test $ iron_worker patch hello -p "hello_worker1.rb=hello_worker.rb"
------> Creating client
        Project 'test' with id='54af65073f116c000500008d'
------> Patching code package 'hello'
        Detected exec with path='/tmp/iron-worker-ng-20150109-6529-asybb4-exec/patchcer.rb' and args='{}'
        Merging file with path='hello_worker1.rb' and dest='patch'
        Patched code package uploaded with id='54afe12308cf462b2a0172ff' and revision='2'
        Check 'https://hud.iron.io/tq/projects/54af65073f116c000500008d/code/54afe12308cf462b2a0172ff' for more info
```

**Comment by sunloverz** [comment]
Uploading and patching this code https://github.com/iron-io/iron_worker_examples/tree/master/ruby_ng/hello_worker
```
tyler@durden ~/test $ iron_worker upload hello 
------> Creating client
        Project 'test' with id='54af65073f116c000500008d'a
------> Creating code package
        Found workerfile with path='hello.worker'
        Detected exec with path='hello_worker.rb' and args='{}'
        Code package name is 'hello'
------> Uploading code package 'hello'
        Code package uploaded with id='54afe12308cf462b2a0172ff' and revision='1'
        Check 'https://hud.iron.io/tq/projects/54af65073f116c000500008d/code/54afe12308cf462b2a0172ff' for more info
tyler@durden ~/test $ iron_worker patch hello -p "hello_worker1.rb=hello_worker.rb"
------> Creating client
        Project 'test' with id='54af65073f116c000500008d'
------> Patching code package 'hello'
        Detected exec with path='/tmp/iron-worker-ng-20150109-6529-asybb4-exec/patchcer.rb' and args='{}'
        Merging file with path='hello_worker1.rb' and dest='patch'
        Patched code package uploaded with id='54afe12308cf462b2a0172ff' and revision='2'
        Check 'https://hud.iron.io/tq/projects/54af65073f116c000500008d/code/54afe12308cf462b2a0172ff' for more info
```

**Comment by thousandsofthem** [comment]
Found it. kind of edge case.
https://github.com/iron-io/iron_worker_ruby_ng/blob/master/lib/iron_worker_ng/client.rb#L175
this line. returning 30 codes at max (one page, default per-page value), my project contain more than that and somehow newly uploaded code present on some other page.
Thoughts how to fix it:
(1) bandaid. just increase number of returned results to allowed max - 100
(2) full-featured solution. iterate over pages until given name is found or returned results number is smaller than max results possible per page

**Comment by sunloverz** [comment]
ok, thanx!

**Comment by sunloverz** [comment]
Done, just increased the max number

**Pull request merged**
