### PR TITLE
Add @iron_schedule_id

### PR DESCRIPTION
**Pull request by pyeremenko**
https://trello.com/c/U9wt8YHG/204-pass-schedule-id-to-task-info-or-make-available-from-within-ironworker-task

### CODE REVIEW

**Comment by pyeremenko** [comment]
Results available here: https://staging-hud.iron.io/tq/projects/54894228b50dfe0009000003/tasks/55092c4c1555d43dde000012

https://github.com/iron-io/simple_worker_backend/pull/261 This code already is in master of simple_worker_backend.

**Comment by thousandsofthem** [comment]
looks good for me. How about other runners inside this gem? (e.g. php, node)

**Comment by pyeremenko** [comment]
@thousandsofthem, ok, I'll add. I'm confused a bit with "(e.g. php, node)" because this feature could be added **only** to php and node. 

So, let's clarify which environments should be improved:

* binary - *no*
* go - *no*
* java - *no*
* mono - *no*
* node - **yes**
* perl - *no*
* php - **yes**
* python - *no*
* ruby - **done**

**Comment by pyeremenko** [comment]
Added php and node but not tested on staging yet...

**Comment by thousandsofthem** [comment]
Thanks!

**Pull request merged**
